### ISSUE TITLE
About tree generator resources 

### ISSUE THREAD

**Issue by QiuHong-1202** [RyuZhihao123/CHITreeProject#1]
Thanks for you excellent work!

I encountered some error when using your tree generator program. The resource files like L-system rules and tree textures seems not included in this repo. Besides, they have been hard coded with absloute path. Would you mind to fix this issue?

![1709519337994_d](https://github.com/RyuZhihao123/CHITreeProject/assets/54990261/9863059f-4b03-42a4-862d-6e59657664e4)

**Comment by RyuZhihao123** [comment]
Thanks for the issue report.
I'd like to double check a few points beforehand: On your PC, could my software generate the 3D trees with the built-in L-system normally? And if the ""Get New Tree" button works or not.

**Comment by RyuZhihao123** [comment]
Oh. I understand
